"""Build ready-to-use files and previews, or check them without writing anything."""
import argparse
from html import escape
import json
from pathlib import Path
import re
import sys

from color import wcag
from palette import build_palette
from export import (KINDS, theme_context, palette_colors, tokens_css,
                    vscode_theme, ghostty_theme, obsidian_css)
from package import vscode_package, vsix_bytes, zip_bytes
import review

ROOT = Path(__file__).resolve().parent.parent
NOTICE = 'THIRD_PARTY_NOTICES.md'


def json_bytes(value):
    return (json.dumps(value, ensure_ascii=False, indent=2) + '\n').encode('utf-8')


def preview_html(pal, css):
    ui, _, _ = theme_context(pal, 'paper')
    def token_button(token, label, value, cls):
        return (f'<button type="button" class="{cls}" data-token="{token}" '
                f'data-label="{label}" data-copy="{value}" aria-label="Copy {label}, {value}" disabled>'
                f'<span class="swatch" style="background:var(--lu-{token})"></span>'
                f'<span><span class="color-name">{label}</span>'
                f'<code class="color-value">{value}</code></span></button>')
    roles = '\n'.join(token_button(key, label, ui[key], 'role')
                      for key, label in [('bg', 'Background'), ('tx', 'Text'), ('link', 'Link')])
    accents = '\n'.join(token_button(f'accent-{name}', name.capitalize(), scale[600]['hex'], 'accent')
                        for name, scale in pal['accents'].items())
    def color_button(name, value, label=None):
        foreground = max((pal['special']['black'], pal['special']['white']), key=lambda c: wcag(c, value))
        return (f'<button type="button" class="scale-color" data-copy="{value}" '
                f'aria-label="Copy {escape(label or name)}, {value}" '
                f'style="background:{value};color:{foreground}" disabled>'
                f'<span>{escape(name)}</span><code>{value}</code></button>')
    groups = {'Base': pal['base'], 'Paper base': pal['paper']['base'],
              **{name.capitalize(): scale for name, scale in pal['accents'].items()}}
    scales = []
    for title, colors in groups.items():
        scales.append(f'<h3>{title}</h3><div class="scale">' +
                      ''.join(color_button(str(step), v['hex'], f'{title} {step}') for step, v in colors.items()) + '</div>')
    special = {name: value for name, value in palette_colors(pal).items()
               if name in ('white', 'black') or name.startswith(('page-', 'hl-'))}
    scales.append('<h3>Backgrounds and highlights</h3><div class="scale small-scale">' +
                  ''.join(color_button(name, value) for name, value in special.items()) + '</div>')
    template = (ROOT / 'scripts/preview.html').read_text(encoding='utf-8')
    for marker, value in [('TOKENS', css), ('ROLES', roles), ('ACCENTS', accents), ('SCALES', '\n'.join(scales))]:
        template = template.replace(f'@@{marker}@@', value)
    return template


def color_reference(pal):
    lines = ['# Palette', '',
             'Generated by `python3 scripts/build.py`. Edit `scripts/palette.py` to change colors.', '',
             '`palette.json` contains every color and role assignment. `tokens.css` contains',
             'the named colors and appearance-specific CSS variables. Both files are ready to use.', '',
             '```html', '<link rel="stylesheet" href="tokens.css">',
             '<div data-lu-theme="paper" style="background:var(--lu-bg);color:var(--lu-tx)">',
             '  Lucretia Paper', '</div>', '```', '',
             'Use `light`, `dark`, or `paper`. All CSS names start with `--lu-`.',
             'UI roles use `--lu-<role>`, syntax uses `--lu-syntax-<role>`, and Markdown',
             'uses `--lu-markdown-<role>`. For example, `--lu-link` and `--lu-syntax-keyword`.', '',
             '## Colors', '', '| Name | HEX | CSS variable |', '| --- | --- | --- |']
    lines += [f'| {name} | `{value}` | `--lu-{name}` |' for name, value in palette_colors(pal).items()]
    lines += ['', '## UI roles', '', '| Role | Light | Dark | Paper |', '| --- | --- | --- | --- |']
    contexts = [theme_context(pal, k)[0] for k in KINDS]
    for role in ('bg', 'bg-2', 'tx', 'tx-2', 'tx-3', 'ui', 'ui-2', 'ui-3', 'link', 'link-hover', 'visited', 'focus-ring'):
        lines.append(f'| {role} | ' + ' | '.join(f'`{c[role]}`' for c in contexts) + ' |')
    lines += ['', 'Additional presentation, chart, gallery, highlight, and text-profile roles',
              'are in `palette.json`. JSON step keys are strings, such as `"600"`.', '',
              'See `THIRD_PARTY_NOTICES.md` for attribution.', '']
    return '\n'.join(lines)


def render():
    """Compute every output before updating files."""
    version = (ROOT / 'VERSION').read_text(encoding='utf-8').strip()
    if not re.fullmatch(r'\d+\.\d+\.\d+', version):
        raise ValueError('VERSION must contain a three-part version, for example 0.3.0')
    pal = build_palette()
    notice = (ROOT / NOTICE).read_bytes()
    css = tokens_css(pal)
    pkg = vscode_package(version)
    extension_readme = (
        '# Lucretia\n\nLight, Dark, and Paper color themes for code and notes.\n\n'
        'Run **Preferences: Color Theme** and choose a Lucretia appearance.\n\n'
        '[Source and installation](https://github.com/sk-226/lucretia)\n\n'
        'Inspired by Flexoki. See THIRD_PARTY_NOTICES.md.\n')
    extension = {'package.json': json_bytes(pkg), 'README.md': extension_readme.encode(), NOTICE: notice}
    for kind in KINDS:
        extension[f'themes/lucretia-{kind}-color-theme.json'] = json_bytes(vscode_theme(pal, kind))
    obsidian_manifest = {'name': 'Lucretia', 'version': version, 'minAppVersion': '1.0.0',
                         'author': 'sk-226', 'authorUrl': 'https://github.com/sk-226'}
    obsidian = {'Lucretia/manifest.json': json_bytes(obsidian_manifest),
                'Lucretia/theme.css': obsidian_css(pal).encode(), f'Lucretia/{NOTICE}': notice}
    outputs = {
        'dist/palette/palette.json': json_bytes(pal),
        'dist/palette/tokens.css': css.encode(),
        'dist/palette/README.md': color_reference(pal).encode(),
        'dist/vscode/lucretia-theme.vsix': vsix_bytes(pkg, extension),
        'dist/obsidian/Lucretia.zip': zip_bytes(obsidian),
        'dist/obsidian/lucretia-minimal.css': obsidian_css(pal, minimal=True).encode(),
        'docs/index.html': preview_html(pal, css).encode(),
    }
    for kind in KINDS:
        outputs[f'dist/ghostty/Lucretia {kind.capitalize()}'] = ghostty_theme(pal, kind).encode()
    for folder in ('palette', 'vscode', 'obsidian', 'ghostty'):
        outputs[f'dist/{folder}/{NOTICE}'] = notice
    for name in ('swatches', 'contrast', 'cvd', 'roles', 'overview', 'degrade', 'paper'):
        content = getattr(review, f'html_{name}')(pal)
        outputs[f'review/{name}.html'] = content.encode()
    return outputs


def output_files(root):
    paths = {p.relative_to(root).as_posix() for folder in ('dist', 'review')
             for p in (root / folder).rglob('*') if p.is_file() and p.name != '.DS_Store'}
    if (root / 'docs/index.html').is_file():
        paths.add('docs/index.html')
    return paths


def differences(root, outputs):
    errors = []
    for name, expected in outputs.items():
        path = root / name
        if not path.is_file():
            errors.append(f'Missing: {name}')
        elif path.read_bytes() != expected:
            errors.append(f'Stale: {name}')
    errors += [f'Unexpected output: {name}' for name in sorted(output_files(root) - outputs.keys())]
    return errors


def write_outputs(root, outputs):
    # Only these documented, generator-owned locations are cleaned.
    for name in output_files(root) - outputs.keys():
        (root / name).unlink()
    for name, content in outputs.items():
        path = root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
    for folder in ('dist', 'review'):
        for path in sorted((root / folder).rglob('*'), reverse=True):
            if path.is_dir() and not any(path.iterdir()):
                path.rmdir()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail on missing, stale, or extra outputs. Write nothing.')
    args = parser.parse_args()
    try:
        outputs = render()
        if args.check:
            errors = differences(ROOT, outputs)
            if errors:
                print('\n'.join(errors), file=sys.stderr)
                return 1
            print(f'All {len(outputs)} generated files match.')
        else:
            write_outputs(ROOT, outputs)
            print(f'Built {len(outputs)} files in dist/, docs/index.html, and review/.')
    except (OSError, ValueError) as error:
        print(f'Build failed: {error}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
