"""Generate self-contained Vim / Neovim colorschemes from the shared palette."""
from export import ANSI_NAMES, ansi, selection_color, theme_context


def vim_theme(pal, kind):
    ui, syn, md = theme_context(pal, kind)
    light = kind != 'dark'
    bg, bg2, tx, tx2, tx3 = (ui[k] for k in ('bg', 'bg-2', 'tx', 'tx-2', 'tx-3'))
    selection = selection_color(pal, light)

    def accent(name, light_step=600, dark_step=300):
        return pal['accents'][name][light_step if light else dark_step]['hex']

    error, warning, info, hint = (accent(n) for n in ('red', 'orange', 'blue', 'cyan'))
    added = accent('green', dark_step=400)
    search = pal['highlight']['yellow']['hex'] if light else accent('yellow', dark_step=850)
    current_search = accent('yellow', 600, 300)
    lines = [f'" Lucretia {kind.capitalize()}. Generated by scripts/build.py.',
             '" Requires true color. See README.md and THIRD_PARTY_NOTICES.md.', '',
             'unlet! g:colors_name', f'set background={"light" if light else "dark"}',
             'highlight clear', "if exists('syntax_on')", '  syntax reset', 'endif',
             f"let g:colors_name = 'lucretia-{kind}'", '']

    def hi(name, fg='NONE', bg='NONE', style='NONE', sp='NONE', indent=''):
        # Spell / diagnostic underlines must not replace the syntax foreground.
        cterm = style.replace('undercurl', 'underline')
        lines.append(f'{indent}highlight {name} guifg={fg} guibg={bg} guisp={sp} '
                     f'gui={style} ctermfg=NONE ctermbg=NONE cterm={cterm} term=NONE')

    def link(name, target, indent=''):
        lines.append(f'{indent}highlight! link {name} {target}')

    lines.append('" Editor')
    hi('Normal', tx, bg)
    hi('Cursor', bg, tx)
    hi('CursorLine', bg=bg2)
    hi('ColorColumn', bg=bg2)
    hi('LineNr', tx3)
    hi('CursorLineNr', tx2, style='bold')
    hi('SignColumn', bg=bg)
    hi('FoldColumn', tx3, bg)
    hi('Folded', tx2, bg2)
    hi('NonText', ui['ui-3'])
    hi('Whitespace', ui['ui-2'])
    hi('EndOfBuffer', ui['ui-3'])
    hi('Conceal', tx3)
    hi('VertSplit', ui['ui-3'], bg)
    hi('StatusLine', tx2, bg2)
    hi('StatusLineNC', tx3, bg2)
    hi('TabLine', tx2, bg2)
    hi('TabLineSel', tx, bg, 'bold')
    hi('TabLineFill', bg=bg2)
    hi('Title', tx, style='bold')
    hi('Directory', ui['link'])
    hi('Visual', bg=selection)
    hi('Search', tx, search)
    hi('IncSearch', pal['special']['black'], current_search, 'bold')
    hi('MatchParen', tx, ui['ui'], 'bold')
    hi('Pmenu', tx, bg2)
    hi('PmenuSel', tx, selection)
    hi('PmenuKind', tx2, bg2)
    hi('PmenuExtra', tx2, bg2)
    hi('PmenuSbar', bg=ui['ui'])
    hi('PmenuThumb', bg=ui['ui-3'])
    hi('PmenuMatch', info, style='bold')
    hi('PmenuMatchSel', tx, style='bold')
    hi('ModeMsg', tx2, style='bold')
    hi('MoreMsg', ui['link'])
    hi('Question', ui['link'])
    hi('WarningMsg', warning)
    hi('ErrorMsg', error)
    hi('QuickFixLine', bg=selection)
    for name, target in {
        'NormalNC': 'Normal', 'Terminal': 'Normal', 'lCursor': 'Cursor',
        'CursorIM': 'Cursor', 'TermCursor': 'Cursor', 'CursorColumn': 'CursorLine',
        'LineNrAbove': 'LineNr', 'LineNrBelow': 'LineNr',
        'CursorLineSign': 'SignColumn', 'CursorLineFold': 'FoldColumn',
        'SpecialKey': 'NonText', 'WinSeparator': 'VertSplit',
        'StatusLineTerm': 'StatusLine', 'StatusLineTermNC': 'StatusLineNC',
        'WinBar': 'StatusLine', 'WinBarNC': 'StatusLineNC',
        'VisualNOS': 'Visual', 'CurSearch': 'IncSearch', 'Substitute': 'IncSearch',
        'PmenuKindSel': 'PmenuSel', 'PmenuExtraSel': 'PmenuSel', 'WildMenu': 'PmenuSel',
        'MsgArea': 'Normal', 'MsgSeparator': 'VertSplit',
    }.items():
        link(name, target)

    lines += ['', '" Syntax: variables stay neutral.']
    hi('Comment', syn['comment'], style='italic')
    hi('Identifier', tx)
    hi('Function', syn['definition'])
    hi('Type', syn['definition'])
    hi('Statement', syn['keyword'])
    hi('PreProc', syn['keyword'])
    hi('String', syn['string'])
    hi('Constant', syn['number'])
    hi('Operator', syn['operator'])
    hi('Special', syn['operator'])
    hi('Underlined', ui['link'], style='underline')
    hi('Ignore', bg)
    hi('Error', error, style='underline', sp=error)
    hi('Todo', tx, search, 'bold')
    for name, target in {
        'Character': 'String', 'Number': 'Constant', 'Boolean': 'Constant',
        'Float': 'Constant', 'Conditional': 'Statement', 'Repeat': 'Statement',
        'Label': 'Statement', 'Keyword': 'Statement', 'Exception': 'Statement',
        'Include': 'PreProc', 'Define': 'PreProc', 'Macro': 'PreProc',
        'PreCondit': 'PreProc', 'StorageClass': 'Statement', 'Structure': 'Statement',
        'Typedef': 'Type', 'SpecialChar': 'Constant', 'Delimiter': 'Operator',
        'SpecialComment': 'Comment', 'Debug': 'Statement', 'Tag': 'Type',
    }.items():
        link(name, target)

    lines += ['', '" Diff and spelling']
    hi('Added', added)
    hi('Changed', info)
    hi('Removed', error)
    # Background-only diff highlights keep syntax colors readable.
    hi('DiffAdd', bg=accent('green', 50, 950))
    hi('DiffChange', bg=accent('blue', 50, 950))
    hi('DiffDelete', error, accent('red', 50, 950))
    hi('DiffText', bg=accent('blue', 150, 850), style='bold')
    link('DiffTextAdd', 'DiffText')
    for name, value in {'SpellBad': error, 'SpellCap': info,
                        'SpellRare': warning, 'SpellLocal': hint}.items():
        hi(name, style='undercurl', sp=value)

    lines += ['', '" Prose uses typography rather than a heading color cycle.']
    hi('LucretiaHeading', md['heading'], style='bold')
    hi('LucretiaBold', style='bold')
    hi('LucretiaItalic', style='italic')
    hi('LucretiaBoldItalic', style='bold,italic')
    hi('LucretiaStrike', style='strikethrough')
    hi('LucretiaUnderline', style='underline')
    hi('LucretiaQuote', md['quote-text'], style='italic')
    hi('LucretiaCode', tx, md['code-inline-bg'])
    hi('LucretiaLink', md['link'], style='underline')
    for name, target in {
        'Bold': 'LucretiaBold', 'Italic': 'LucretiaItalic',
        'BoldItalic': 'LucretiaBoldItalic',
        'markdownBold': 'LucretiaBold', 'markdownItalic': 'LucretiaItalic',
        'markdownBoldItalic': 'LucretiaBoldItalic', 'markdownStrike': 'LucretiaStrike',
        'markdownBlockquote': 'LucretiaQuote', 'markdownCode': 'LucretiaCode',
        'markdownCodeBlock': 'LucretiaCode', 'markdownCodeDelimiter': 'Delimiter',
        'markdownHeadingDelimiter': 'Delimiter', 'markdownRule': 'Delimiter',
        'markdownUrl': 'LucretiaLink', 'markdownLinkText': 'LucretiaLink',
        'markdownLinkDelimiter': 'Delimiter', 'markdownLinkTextDelimiter': 'Delimiter',
        'markdownListMarker': 'Delimiter', 'markdownOrderedListMarker': 'Delimiter',
        'htmlBold': 'LucretiaBold', 'htmlItalic': 'LucretiaItalic',
        'htmlBoldItalic': 'LucretiaBoldItalic', 'htmlUnderline': 'LucretiaUnderline',
        'htmlStrike': 'LucretiaStrike',
        'texSection': 'LucretiaHeading', 'texTitle': 'LucretiaHeading',
        'texBoldStyle': 'LucretiaBold', 'texItalStyle': 'LucretiaItalic',
        'texRefZone': 'Function', 'texCite': 'Function',
    }.items():
        link(name, target)
    for level in range(1, 7):
        link(f'markdownH{level}', 'LucretiaHeading')
        link(f'htmlH{level}', 'LucretiaHeading')

    lines += ['', "if has('nvim')", '  " Floating windows and built-in LSP UI']
    hi('NormalFloat', tx, bg2, indent='  ')
    hi('FloatBorder', ui['ui-3'], bg2, indent='  ')
    hi('FloatTitle', tx, bg2, 'bold', indent='  ')
    hi('FloatFooter', tx2, bg2, indent='  ')
    hi('LspInlayHint', tx3, bg2, indent='  ')
    hi('LspCodeLens', tx3, indent='  ')
    hi('LspSignatureActiveParameter', style='bold', indent='  ')
    for name, target in {
        'LspCodeLensSeparator': 'LspCodeLens', 'LspReferenceText': 'Visual',
        'LspReferenceRead': 'Visual', 'LspReferenceWrite': 'Visual',
        'LspReferenceTarget': 'Visual', 'SnippetTabstop': 'Visual',
        'SnippetTabstopActive': 'Visual', 'PmenuBorder': 'FloatBorder',
        'PreInsert': 'Comment', 'ComplHint': 'Comment', 'ComplHintMore': 'Comment',
        'OkMsg': 'Added', 'StderrMsg': 'ErrorMsg', 'StdoutMsg': 'Normal',
    }.items():
        link(name, target, '  ')
    for severity, value in {'Error': error, 'Warn': warning, 'Info': info,
                            'Hint': hint, 'Ok': added}.items():
        hi(f'Diagnostic{severity}', value, indent='  ')
        for suffix in ('Sign', 'Floating', 'VirtualText', 'VirtualLines'):
            link(f'Diagnostic{suffix}{severity}', f'Diagnostic{severity}', '  ')
        hi(f'DiagnosticUnderline{severity}', style='undercurl', sp=value, indent='  ')
    hi('DiagnosticUnnecessary', tx3, indent='  ')
    hi('DiagnosticDeprecated', style='strikethrough', indent='  ')

    lines.append('  " Tree-sitter captures (including built-in overrides)')
    captures = {
        'variable': 'Identifier', 'variable.builtin': 'Identifier',
        'variable.parameter': 'Identifier', 'variable.parameter.builtin': 'Identifier',
        'variable.member': 'Identifier', 'property': 'Identifier',
        'module': 'Identifier', 'module.builtin': 'Identifier',
        'constant': 'Constant', 'constant.builtin': 'Constant', 'constant.macro': 'Constant',
        'string': 'String', 'string.documentation': 'Comment', 'string.regexp': 'String',
        'string.escape': 'SpecialChar', 'string.special': 'String',
        'string.special.symbol': 'Constant', 'string.special.url': 'LucretiaLink',
        'character': 'Character', 'character.special': 'SpecialChar',
        'boolean': 'Boolean', 'number': 'Number', 'number.float': 'Float',
        'type': 'Type', 'type.builtin': 'Type', 'type.definition': 'Type',
        'attribute': 'PreProc', 'attribute.builtin': 'PreProc',
        'function': 'Function', 'function.builtin': 'Function', 'function.method': 'Function',
        'function.call': 'Identifier', 'function.method.call': 'Identifier',
        'function.macro': 'Macro', 'constructor': 'Type', 'operator': 'Operator',
        'keyword': 'Keyword', 'keyword.operator': 'Operator', 'label': 'Label',
        'punctuation': 'Delimiter', 'punctuation.delimiter': 'Delimiter',
        'punctuation.bracket': 'Delimiter', 'punctuation.special': 'Delimiter',
        'comment': 'Comment', 'comment.documentation': 'Comment',
        'comment.error': 'DiagnosticError', 'comment.warning': 'DiagnosticWarn',
        'comment.todo': 'Todo', 'comment.note': 'DiagnosticInfo',
        'markup': 'Identifier', 'markup.strong': 'LucretiaBold',
        'markup.italic': 'LucretiaItalic', 'markup.strikethrough': 'LucretiaStrike',
        'markup.underline': 'LucretiaUnderline', 'markup.heading': 'LucretiaHeading',
        'markup.quote': 'LucretiaQuote', 'markup.math': 'Identifier',
        'markup.link': 'LucretiaLink', 'markup.link.label': 'LucretiaLink',
        'markup.link.url': 'LucretiaLink', 'markup.raw': 'LucretiaCode',
        'markup.raw.block': 'LucretiaCode', 'markup.list': 'Delimiter',
        'markup.list.checked': 'Comment', 'markup.list.unchecked': 'Delimiter',
        'diff.plus': 'Added', 'diff.minus': 'Removed', 'diff.delta': 'Changed',
        'tag': 'Type', 'tag.builtin': 'Type', 'tag.attribute': 'Identifier',
        'tag.delimiter': 'Delimiter',
    }
    for level in range(1, 7):
        captures[f'markup.heading.{level}'] = 'LucretiaHeading'
    for name, target in captures.items():
        link(f'@{name}', target, '  ')

    lines.append('  " LSP tokens: keep variables neutral; preserve syntax for function calls.')
    for name, target in {
        'variable': 'Identifier', 'parameter': 'Identifier', 'property': 'Identifier',
        'namespace': 'Identifier', 'event': 'Identifier',
        'class': 'Type', 'enum': 'Type', 'interface': 'Type', 'struct': 'Type',
        'type': 'Type', 'typeParameter': 'Type', 'enumMember': 'Constant',
        'macro': 'Macro', 'decorator': 'PreProc', 'keyword': 'Keyword',
        'modifier': 'Keyword', 'comment': 'Comment', 'string': 'String',
        'number': 'Number', 'regexp': 'String', 'operator': 'Operator',
    }.items():
        link(f'@lsp.type.{name}', target, '  ')
    for name in ('function', 'method'):
        hi(f'@lsp.type.{name}', indent='  ')
        for modifier in ('declaration', 'definition'):
            link(f'@lsp.typemod.{name}.{modifier}', 'Function', '  ')
    link('@lsp.mod.deprecated', 'DiagnosticDeprecated', '  ')

    lines.append('  " ANSI colors for new :terminal buffers')
    terminal = ansi(pal, kind)
    for index, name in enumerate(ANSI_NAMES):
        lines.append(f"  let g:terminal_color_{index} = '{terminal[name]}'")
    lines += ['else', '  let g:terminal_ansi_colors = [']
    lines += [f"        \\ '{terminal[name]}'," for name in ANSI_NAMES]
    lines += ['        \\ ]', 'endif', '']
    return '\n'.join(lines)
